language: node_js
node_js:
  - "14"
install:
  - npm install
script:
  - npm run build
  - npm run lint
  - npm run coverage
  - npm run build:example
after_success:
  - cat ./coverage/*.info | ./node_modules/coveralls/bin/coveralls.js
cache:
  directories:
    - node_modules
deploy:
  - provider: releases
    api_key:
      secure: "NcL1OIOHWzgfVsce8LSHFqjuRE0KpvCQ/C5fS89gX+ipX1hf0dpMxRt5XXvAvS7Wyc+2bpx9RVAAH20dFvFBv4ZqvFxcEU/ZdRSZ1MMEbU/4SSI6kN8nPCXHcg2naWeJqp8C+o70ofw1bs6eLX3pmx9n6QhtG5jDHLP2nJjrf+7UIW7HgdxYbrKJi/JsE+nyp3Yx5p01926AZL6mFJPWdysVG4SkM4B4APPoLX+UvDCl6VcWXaAl53c22jWYgbTbyy6PuULNC+hlzRdxBfOd23r7ScGP7SizlBJAvDza0Ol1ZSewkSsRI4Kun1Xslc3VFPX/GhomitOu3RN7ZG7NfzxAnc7inaYOaQwWBKdYDvRm3Zj1cnfzuAljhALYwlfqYwA12TOfGFul2a2MaJpQpy4DgaRtM9sWzJzjbYu8SKmsY7oreeaRwM0vCkg1PhRyF6x4ydfWmObUFSqLFdpcJ3dzxMW3y/JwLTLpZ11cyoB5EnCi1owxR0fLyagEWRPvy00y9KbuWbhsjC2v9zwpTftib6zT1JezImDZXOXUiHeRRmXYtHwNc1OrsXfDiHKEao1hygVbdbCVWHdYgWJ7aEB0mtJFLOyFopq3fovR7Rj7icSjCbnIHfcvqWHVrKTRw16UZ5Cy5jtByi9Ogz4l9KBP9kRcUk5pIdnPdimkZEk="
    skip_cleanup: true
    on:
      tags: true
      repo: manubb/react-ace-builds
      branch: local
  - provider: npm
    edge: true
    email: mbaclet@gmail.com
    api_key:
      secure: "RSFG8Xxgsuj8SKVlzV9gyW5Td6wX3Lbvq3n7LP9XSLw9PsEGeO57EoXhRkOfs6IEkDZww3wO4KxqQIYEXbm03C5W7g1ou9zE+utkk5niWmI4pnTTizz8jOnsUsdvLLq51ZeE6j1pUhdQkBw1m17xOIf+u2kmWk6EoavBB7Io7vXwg+Rzq//jTSLrISX0xH9njPEvqe+vkY3AUdXURQRqALAyLSgDghaCyJcIskcgUhYfLAcLRJhq868/VqsD07ze7A6bc+2H+0uQX2O4BXeAE/lyOOCZJWM7h6itSa7mVSk6EkpuemFHmga2T9OL5FEoxEpexA4O9A/dFBh4wflK8HcIAuT+eOTY2asEx6JtUd9pZn+IShpjw//gIBSExJ5p3TEgyRBViMFfi5q/jMXE/VL49NsHKVfeTRglyrLNf/Nppz/OGgivyUuZYr26qhW3Ie7NyHsiQ7gbF8YnqwbLcUhPEsOhFeEBtXs+oohengWveJ3M2pwCN/HhfTB3fFYP7NZng/5NaoZfwYiaCa7REProOWRWpcFSx+ZB3+ihYzdjcNQv/hfx9XqfwmiZwQgWUpwux3LkG42hckvzWW4xiED99i1LzX6/HdYMt7pPEwLGbsnYh02bzFkpGTF4Sr2NwCoeYeS387kAl7jTXZfZrPx2FVZZ3jJMzdiKws0w8R8="
    skip_cleanup: true
    on:
      tags: true
      repo: manubb/react-ace-builds
      branch: local
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: local
      repo: manubb/react-ace-builds
    local_dir: example
