language: node_js
node_js:
  - "14"
install:
  - npm install
script:
  - npm run build
  - npm run lint
  - npm run coverage
  - npm run build:example
after_success:
  - cat ./coverage/*.info | ./node_modules/coveralls/bin/coveralls.js
cache:
  directories:
    - node_modules
deploy:
  - provider: releases
    api_key:
      secure: 03xGh43El9WF1UNFrP3bWVWl4mkSsGP7fNE7EKiA33maybMT46QwXj+8nOkgeHUHlWE0+jPyg0GRSjTS7/FW52IsknCIZdAKR+bZvUmic/zOQYXcQmRCnIxTzCKaKDPKuRXWmObS1IzUo9BUeFyY+ow8+Sam7EiXHzCHL5fbyoZsLdRt9a/hx1+5RZvH7zvU7JqDRDY4rHa40M1wAh3wPX30IEaaTNfpuRZvebVuvHjYnT6lfPohuJAqmwb9Opl1WPkhVhs8dvpWFWL2Qk+vF+Adaqv0tn6tscQkj0wVBsFQkBqESPK35noY1FruU6Uw8Es89IeueCi06R7+PI8LWaSMYtOVzNKUN0rYL39K+UUCi4MIwVnpow2WSJ5bxdlIfVG7zVz1NuAg/qUVQRjM5RztbkdH4MWwnWdhLbclNdiPIgesY+N2Ta93FxL/2FjTVTrYDcXEW16Xfk6RXM6xa7ZAZNnKT2Twko5qvwBalbvKRj+2S3QDMy3S9z+/Mxq5iQvfXyxCrT2A4f/YJj3gsypUL+e+Ee+KHDIGQ/Ie41ZAzXnC4QmgVcnVLHdgCMxOcV8EQxCm/K6Ngi8ce06USqeKa/+Dk8BR8gCtnvEG2twxqdUWjv4ZQ3pJwSwVG8sEhQ/Tr7g5at8pTs29DTfQoc3lyRNtV4m+NNaUStU+fdg=
    skip_cleanup: true
    on:
      tags: true
      repo: manubb/react-ace-builds
      branch: local
  - provider: npm
    edge: true
    email: mbaclet@gmail.com
    api_key:
      secure: 1K5bsJGtvYMn3ky4L/XDyyBXC9wApHGcZGgHDZpVaSSX8RnBsFZB2CNkpO9U9lW645uQ+aF7EzS07E2Nd4B3CwipIEMfgW4s79vibN0Yiy8MbPn4WKARzmYbHhEVT8IDFwdOxovlhQedq9kB8xjfTxf0tFV+JQht+vb0JnFlFL5CMjlePT2enMh2yqVBAImL10FM2Cm0d4Y0EGe0vjapNPfP6Hk8jgAmdl3Eh7Kr/47yLo0tafm5HZARQDrCambHh54JZTYRiE/hjgmAkiQzfeKX+0egJRqeU22mMK5oWfJiA/W05fZkANnKwY1912+VL0kfUc1DDP59g0QvuA8oOmCQ26mDliMVKZrjGMW5OVOYjX+tk1QGOUUgaQJ3D/jHwHPuFUhTEb0L/sQfniAfG8TYeepKPNnzAu9/k8K+gHVUv3jMcoNTC1/I9iATOwwmC/LTytQi1ca2a17XM981tNPFwFAMhvL0bHtxYjC34ysCHoGMVDpQ/w2F6VW3vhn12Hqama+hws6BPW2R8hzOAYGi5DK/MdrpjIfNVMwe56iWhuAICVHACx2MbIKoNfeEiC8huN+Ww3YBGG6OvIDEYEqMKWk9lu+KSkzT41MO9EA60Mbw8aSLctlLqc/QU0rW0jdgY3jiSs3hzDLTpaThat/aKTHLENE6GNbqZZGxFjM=
    skip_cleanup: true
    on:
      tags: true
      repo: manubb/react-ace-builds
      branch: local
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    on:
      branch: local
      repo: manubb/react-ace-builds
    local_dir: example
